# Generated by Django 4.0.3 on 2022-03-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=64)),
                ('middlename', models.CharField(max_length=64, null=True)),
                ('firstname', models.CharField(max_length=64)),
                ('phone', models.IntegerField(null=True)),
                ('socialnumber', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=64)),
                ('hexcolor', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.customer')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.product')),
            ],
        ),
    ]
