# Generated by Django 4.0.1 on 2023-10-10 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('length', models.FloatField()),
                ('measurement_unit', models.CharField(choices=[('m', 'meter'), ('y', 'yard')], max_length=64)),
                ('location', models.CharField(max_length=64, null=True)),
                ('product_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64, null=True)),
                ('socialnumber', models.IntegerField(null=True)),
                ('customer_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=64)),
                ('typeKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='management.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.color')),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='colorKey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='management.type'),
        ),
    ]
