# Generated by Django 4.0.1 on 2023-10-12 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='typeKey',
            new_name='product',
        ),
    ]
