# Generated by Django 4.0.1 on 2023-10-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_typekey_type_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='sold',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='Le Thi Rieng', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='deliverer',
            field=models.CharField(default='Ba Gac Hien', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Đã giao', 'Đã giao'), ('Chưa giao', 'Chưa giao'), ('Đang giao', 'Đang giao')], default='Chưa giao', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Chưa thanh toán', 'Chưa thanh toán'), ('Đã thanh toán', 'Đã thanh toán')], default='Chưa thanh toán', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
