# Generated by Django 4.0.3 on 2022-03-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_customer_customer_date_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
