# Generated by Django 4.0.3 on 2022-03-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(choices=[('m', 'meter'), ('y', 'yard')], default='m', max_length=64),
            preserve_default=False,
        ),
    ]
