# Generated by Django 4.0.1 on 2023-10-13 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_color_sold_customer_address_order_deliverer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='typeOfProduct',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='color',
            new_name='colorOfType',
        ),
        migrations.AlterField(
            model_name='color',
            name='colorKey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.product'),
        ),
    ]
