# Generated by Django 4.0.1 on 2023-10-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_rename_type_product_typeofproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='product_date',
            new_name='color_date',
        ),
    ]
