# Generated by Django 4.0.2 on 2022-03-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_product_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(choices=[('m', 'meter'), ('y', 'yard')], default='y', max_length=64),
            preserve_default=False,
        ),
    ]
