# Generated by Django 4.2.6 on 2023-10-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_roll_rename_colorkey_color_typekey_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roll',
            old_name='color_date',
            new_name='roll_date',
        ),
    ]
