# Generated by Django 4.0.3 on 2022-03-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_product_measurement_unit'),
        ('management', '0006_remove_order_product_order_product_id'),
    ]

    operations = [
    ]
