# Generated by Django 4.0.3 on 2022-03-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_merge_20220307_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
    ]
